// create an api for a catering shpe
const catering = [
     {
          name: "Chocolate Cake",
          price: 1000,
          description: "Chocolate Cake with chocolate icing",
          img: "img1.jpg",
          flavor: "Chocolate",
          discount: 10,
          rating: 4.5,
     },
     {
          name: "Vanilla Cake",
          price: 800,
          description: "Vanilla Cake with vanilla icing",
          img: "img2.jpg",
          flavor: "Vanilla",
          discount: 5,
          rating: 4.0,
     },
     {
          name: "Strawberry Cake",
          price: 900,
          description: "Strawberry Cake with strawberry icing",
          img: "img3.jpg",
          flavor: "Strawberry",
          discount: 15,
          rating: 4.7,
     },
     {
          name: "Pineapple Cake",
          price: 600,
          description: "Pineapple Cake with pineapple icing",
          img: "img4.jpg",
          flavor: "Pineapple",
          discount: 20,
          rating: 4.9,
     },
     {
          name: "Butterscotch Cake",
          price: 500,
          description: "Butterscotch Cake with butterscotch icing",
          img: "img5.jpg",
          flavor: "Butterscotch",
          discount: 25,
          rating: 4.8,
     },
     {
          name: "Red Velvet Cake",
          price: 400,
          description: "Red Velvet Cake with red velvet icing",
          img: "img6.jpg",
          flavor: "Red Velvet",
          discount: 30,
          rating: 4.6,
     },
     {
          name: "Black Forest Cake",
          price: 300,
          description: "Black Forest Cake with black forest icing",
          img: "img7.jpg",
          flavor: "Black Forest",
          discount: 35,
          rating: 4.4,
     },
     {
          name: "Blueberry Cake",
          price: 200,
          description: "Blueberry Cake with blueberry icing",
          img: "img8.jpg",
          flavor: "Blueberry",
          discount: 40,
          rating: 4.3,
     },
     {
          name: "Mango Cake",
          price: 100,
          description: "Mango Cake with mango icing",
          img: "img9.jpg",
          flavor: "Mango",
          discount: 45,
          rating: 4.2,
     },
     {
          name: "Lemon Cake",
          price: 50,
          description: "Lemon Cake with lemon icing",
          img: "img10.jpg",
          flavor: "Lemon",
          discount: 50,
          rating: 4.1,
     },{
          name: "sponge Cake",
          price: 50,
          description: "sponge Cake with sponge icing",
          img: "img11.jpg",
          flavor: "sponge",
          discount: 50,
          rating: 4.1,
     },{
          name:"banana Cake",
          price: 50,
          description: "banana Cake with banana icing",
          img: "img12.jpg",
          flavor: "banana",
          discount: 50,
          rating: 4.1,
     },{
          name:"cherry Cake",
          price: 50,
          description: "cherry Cake with cherry icing",
          img: "img13.jpg",
          flavor: "cherry",
          discount: 50,
          rating: 4.1,
     },{
          name:"coconut Cake",
          price: 50,
          description: "coconut Cake with coconut icing",
          img: "img14.jpg",
          flavor: "coconut",
          discount: 50,
          rating: 4.1,
     },{
          name:"coffee Cake",
          price: 50,
          description: "coffee Cake with coffee icing",
          img: "img15.jpg",
          flavor: "coffee",
          discount: 50,
          rating: 4.1,
     },{
          name:"orange Cake",
          price: 50,
          description: "orange Cake with orange icing",
          img: "img16.jpg",
          flavor: "orange",
          discount: 50,
          rating: 4.1,
     },{
          name:"pistachio Cake",
          price: 50,
          description: "pistachio Cake with pistachio icing",
          img: "img17.jpg",
          flavor: "pistachio",
          discount: 50,
          rating: 4.1,
     },{
          name:"raspberry Cake",
          price: 50,
          description: "raspberry Cake with raspberry icing",
          img: "img18.jpg",
          flavor: "raspberry",
          discount: 50,
          rating: 4.1,
     },{
          name:"rose Cake",
          price: 50,
          description: "rose Cake with rose icing",
          img: "img19.jpg",
          flavor: "rose",
          discount: 50,
          rating: 4.1,
     },{
          name:"tiramisu Cake",
          price: 50,
          description: "tiramisu Cake with tiramisu icing",
          img: "img20.jpg",
          flavor: "tiramisu",
          discount: 50,
          rating: 4.1,
     },{
          name: "anise Cake",
          price: 50,
          description: "anise Cake with anise icing",
          img: "img21.jpg",
          flavor: "anise",
          discount: 50,
          rating: 4.1,
     },{
          name: "apple Cake",
          price: 50,
          description: "apple Cake with apple icing",
          img: "img22.jpg",
          flavor: "apple",
          discount: 50,
          rating: 4.1,
     },{
          name: "Bean Cake",
          price: 50,
          description: "Bean Cake made with bean and fried",
          img: "img23.jpg",
          flavor: "Bean",
          discount: 50,
          rating: 4.1,
     }
]

module.exports = catering;